
//this key is my api key I have generated by creating account on https://api.openweathermap.org
const api = {
  key: "bbaf8c7f3f44bacb41aa3c3ca17ffbd7",
  base: "https://api.openweathermap.org/data/2.5/"
}

//trigger getResults function by listening to the event when user presses "Enter Key"
const searchbox = document.querySelector('.search-box');
searchbox.addEventListener('keypress', (evt) => {
  if (evt.key === "Enter") {
    //console.log(evt.target.value);
    getResults(evt.target.value);
    evt.target.value = '';
  }
})

//fetch the results of the API in JSON format- when the response is ok, trigger displayResults function
function getResults(query) {
  fetch(`${api.base}weather?q=${query}&units=metric&appid=${api.key}`)
    .then(weather => {
      if (weather.ok) {
        return weather.json();
      } else {
        console.log("Error: city name invalid");
      }
    }).then((response) => {
      if (response === undefined) {
        console.log("Error!!");
        alert("Enter valid city name or City not found!");
      } else {
        console.log(response)
        displayResults(response);
      }
    });
}

//Replace the context of HTML using innerText, innerHTML from the JSON response, call dateBuilder to format the the date as per required format
function displayResults(weather) {
  let city = document.querySelector('.location .city');
  city.innerText = `${weather.name}, ${weather.sys.country}`;

  let now = new Date();
  let date = document.querySelector('.location .date');
  date.innerText = dateBuilder(now);

  let temp = document.querySelector('.current .temp');
  temp.innerHTML = `${Math.round(weather.main.temp)}<span>°c</span>`;

  let weather_el = document.querySelector('.current .weather');
  weather_el.innerText = weather.weather[0].main;

  let hilow = document.querySelector('.hi-low');
  hilow.innerText = `${Math.round(weather.main.temp_min)}°c / ${Math.round(weather.main.temp_max)}°c`;
}

//Build the dates in the format "Sunday 22 January 2023" i.e. Day Date Month and Year 
function dateBuilder(currentDate) {
  let months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
  let days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

  let day = days[currentDate.getDay()];
  let date = currentDate.getDate();
  let month = months[currentDate.getMonth()];
  let year = currentDate.getFullYear();

  return `${day} ${date} ${month} ${year}`;
}

//get and display weather of Delhi whenever page is loaded initially
window.onload = getResults('Delhi');